### PR TITLE
Test folder partitioning

### PR DESCRIPTION
**Pull request by makcandrov**
#122 point 3

### CODE REVIEW

**Review by Tristan22400 — APPROVED** [review]

**Comment by MathisGD** [comment]
I'm not a big fan of complex folder trees. Checking the initial conversation, I have not seen any evidence showing the benefit of such an re-org. So I'm against (but no veto).

**Comment by makcandrov** [comment]
can be closed if everyone agrees

**Comment by Tristan22400** [comment]
> I'm not a big fan of complex folder trees. Checking the initial conversation, I have not seen any evidence showing the benefit of such an re-org. So I'm against (but no veto).

What could be better in my opinion is to separate the test by datastructure. IT could be more readable. If we want to organize these files.

**Comment by pakim249CAL** [comment]
I think just from a practical standpoint, there aren't that many test files to necessitate a reorganization imo. The morpho-aave-v3 repo definitely needed this though because of the sheer number of tests. If this repo grows further, I think we can reorg at that point.

**Comment by MathisGD** [comment]
>What could be better in my opinion is to separate the test by datastructure. IT could be more readable. If we want to organize these files.

Couldn't good file names do the job ?

**Review by QGarchery — APPROVED** [review]

**Pull request closed without merging**
